[package]
name    = "notification-service"
version = "0.1.0"
edition = "2021"

[lib]
name = "notification_service"
path = "src/lib.rs"

[[bin]]
name = "notification-service"
path = "src/main.rs"

[dependencies]
common-errors  = { workspace = true }
common-tracing = { workspace = true }
common-auth-mw = { workspace = true }
common-rate-limit = { workspace = true }
notification-service-client = { path = "../notification-service-client" }
user-service-client         = { path = "../user-service-client" }
auth-service-client         = { path = "../auth-service-client" }

axum        = { workspace = true }
tokio       = { workspace = true }
sqlx        = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
uuid        = { workspace = true }
chrono      = { workspace = true }
tracing     = { workspace = true }
tower-http  = { workspace = true }
thiserror   = { workspace = true }
dotenvy     = { workspace = true }
anyhow      = { workspace = true }
validator   = { workspace = true }
redis       = { workspace = true }
async-trait = "0.1"
