[package]
name    = "report-service"
version = "0.1.0"
edition = "2021"

[lib]
name = "report_service"
path = "src/lib.rs"

[[bin]]
name = "report-service"
path = "src/main.rs"

[dev-dependencies]
auth-service = { path = "../auth-service" }
tower        = { workspace = true }
dotenvy      = { workspace = true }
bcrypt       = { workspace = true }
serde_json   = { workspace = true }

[dependencies]
common-errors      = { workspace = true }
common-tracing     = { workspace = true }
common-auth-mw     = { workspace = true }
common-rate-limit   = { workspace = true }
common-config       = { workspace = true }
report-service-client         = { path = "../report-service-client" }
notification-service-client   = { path = "../notification-service-client" }
storage-service-client        = { path = "../storage-service-client" }
auth-service-client           = { path = "../auth-service-client" }
async-trait                   = "0.1"

axum        = { workspace = true }
tokio       = { workspace = true }
sqlx        = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
uuid        = { workspace = true }
chrono      = { workspace = true }
tracing     = { workspace = true }
thiserror   = { workspace = true }
validator   = { workspace = true }
dotenvy     = { workspace = true }
anyhow      = { workspace = true }
