[package]
name    = "iklan-pekerjaan-service"
version = "0.1.0"
edition = "2021"

[lib]
name = "iklan_pekerjaan_service"
path = "src/lib.rs"

[[bin]]
name = "iklan-pekerjaan-service"
path = "src/main.rs"

[dependencies]
common-errors  = { workspace = true }
common-tracing = { workspace = true }
common-auth-mw = { workspace = true }
common-rate-limit = { workspace = true }
iklan-pekerjaan-service-client = { path = "../iklan-pekerjaan-service-client" }
user-service-client            = { path = "../user-service-client" }
notification-service-client    = { path = "../notification-service-client" }
storage-service-client         = { path = "../storage-service-client" }
auth-service-client            = { path = "../auth-service-client" }
async-trait                    = "0.1"

axum        = { workspace = true }
tokio       = { workspace = true }
sqlx        = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
uuid        = { workspace = true }
chrono      = { workspace = true }
tracing     = { workspace = true }
tower-http  = { workspace = true }
thiserror   = { workspace = true }
validator   = { workspace = true }
dotenvy     = { workspace = true }
anyhow      = { workspace = true }
ammonia     = { workspace = true }
